library(shiny)
library(shinydashboard)
library(plotly)
library(fontawesome)
library(regclass)
library(ggplot2)
library(reshape2)
library(DT)
library(dplyr)
library(tsibble)
library(shinyWidgets)
library(feasts)
library(forecast)
library(fable)

Tennis <- read.csv("TennisData.csv")
names(Tennis) <- c("Year", "Calendar Year", "Player", "Aces", "Double Faults",
                   "1st Serve %", "% 1st Serve Points Won", "% 2nd Serve Points Won",
                   "Break Points Faced", "% Break Points Saved", "Service Games Played",
                   "% Service Games Won", "% Total Service Points Won", "% 1st Serve Return Points Won",
                   "% 2nd Serve Return Points Won", "Break Points Opportunities",
                   "% Break Points Converted", "Return Games Played", "% Return Games Won",
                   "% Return Points Won", "% Total Points Won")
Tennis[,c(6,7,8,10,12,13,14,15,17,19,20,21)] <- Tennis[,c(6,7,8,10,12,13,14,15,17,19,20,21)]*100

ui <- dashboardPage(skin = "black",
                    dashboardHeader(title = "Tennis Statistics",
                                    dropdownMenu(notificationItem(shinythemes::themeSelector()),
                                                 type = "notifications")),
                    dashboardSidebar(sidebarMenu(
                      menuItem(text = "Instructions", tabName = "instruct", icon = icon("info")),
                      menuItem(text = "Tsibble", tabName = "tsibble", icon = icon("file-csv")),
                      menuItem(text = "Stats by Year", tabName = "table", icon = icon("table")),
                      menuItem(text = "Career Stats", tabName = "table1", icon = icon("table")),
                      menuItem(text = "Player Comparison", tabName = "graph", icon = icon("chart-bar")),
                      menuItem(text = "Transformations", tabName = "transform", icon = icon("chart-line")),
                      menuItem(text = "Simple Models", tabName = "simplemodel", icon = icon("chart-line")),
                      menuItem(text = "Exponential Smoothing", tabName = "ets", icon = icon("chart-line")),
                      menuItem(text = "ARIMA", tabName = "arima", icon = icon("chart-line")),
                      menuItem(text = "Custom ARIMA", tabName = "custarima", icon = icon("chart-line")),
                      menuItem(text = "Linear Regression", tabName = "reg", icon = icon("chart-line")),
                      menuItem(text = "Specific Linear Models", tabName = "linear", icon = icon("chart-line"))
                    )),
                    dashboardBody(
                      tabItems(
                        tabItem(tabName = "instruct", includeMarkdown("TennisAppInstructions.rmd")),
                        tabItem(tabName = "tsibble",
                                box(title = "Let's Turn This Data into a Tsibble!",
                                    selectInput(inputId = "index", label = "What is the Index of this Data?",
                                                choices = c("",names(Tennis)))),
                                box(selectInput(inputId = "key1",
                                                label = "What is the Key of This Data? (Hint: There are Two)",
                                                choices = c("",names(Tennis))),
                                    selectInput(inputId = "key2", label = NULL,
                                                choices = c("",names(Tennis)))),
                                actionButton(inputId = "create", label = "Create!"),
                                DTOutput("tsibble")
                        ),
                        tabItem(tabName = "table",
                                box(title = "Select the Players You Want to See",
                                    multiInput(inputId = "player",
                                               label = NULL,
                                               choiceNames = unique(Tennis[,3]),
                                               choiceValues = unique(Tennis$Player)),
                                    width = 4),
                                box(title = "Select the Years You Want to See",
                                    multiInput(inputId = "careeryear",
                                               label = NULL,
                                               choiceNames = unique(Tennis[,1]),
                                               choiceValues = unique(Tennis$Year)),
                                    width = 4),
                                box(title = "Select the Specific Stats You Want to See",
                                    multiInput(inputId = "yearstat",
                                               label = NULL,
                                               choices = names(Tennis)[4:21]),
                                    width = 4),
                                actionButton(inputId = "compare", label = "Compare"),
                                DTOutput("yearstattable")),
                        tabItem(tabName = "table1",
                                box(title = "Select the Players You Want to See",
                                    multiInput(inputId = "player1",
                                               label = NULL,
                                               choiceNames = unique(Tennis[,3]),
                                               choiceValues = unique(Tennis$Player))),
                                box(title = "Select the Specific Career Stats You Want to See",
                                    multiInput(inputId = "careerstat",
                                               label = NULL,
                                               choices = names(Tennis)[4:21])),
                                actionButton(inputId = "compare1", label = "Compare"),
                                DTOutput("careerstattable")),
                        tabItem(tabName = "graph",
                                box(title = "Select the Type of Comparison you want to Make",
                                    awesomeRadio(
                                      inputId = "graphselect",
                                      label = "If you select 'Yearly Stats', you will be able to 
                  create a time series graph of the player and years of your choosing,
                  along with the statistic of your choosing. If you select 'Career Stats',
                  you will be able to create a line graph that compare the career stats
                  of your chosen players and statistics.",
                                      choices = c("Yearly Stats", "Career Stats")),
                                    width = 4, height = 350),
                                uiOutput("graphoptions"),
                                plotlyOutput("yeargraph"),
                                plotlyOutput("careergraph")),
                        tabItem(tabName = "transform",
                                box(title = "Select the Parameters you Want for your Transformation",
                                    selectInput(inputId = "transformplayer", label = "Select a Player",
                                                choices = c("",unique(Tennis$Player))),
                                    selectInput(inputId = "transformstat", label = "Select a Statistic",
                                                choices = c("",names(Tennis)[4:21]))),
                                box(title = "Select the Transformation you Would Like to Do",
                                    selectInput(inputId = "transformmodel", label = "Select a Model Type",
                                                choices = c("","Square Root","Cube Root","Logarithm","Inverse","Box-Cox"))),
                                actionButton(inputId = "create2", label = "Create!"),
                                br(), br(), br(), br(), br(), br(),
                                plotlyOutput("transform")),
                        tabItem(tabName = "simplemodel",
                                box(title = "Select the Output you want to See with your Created Model",
                                    awesomeRadio(
                                      inputId = "simplegraph",
                                      label = NULL,
                                      choices = c("Forecast", "Residuals", "Accuracy")),
                                    width = 4),
                                box(title = "Select the Parameters you Want for your Model",
                                    selectInput(inputId = "simpleplayer", label = "Select a Player",
                                                choices = c("",unique(Tennis$Player))),
                                    selectInput(inputId = "simplestat", label = "Select a Statistic",
                                                choices = c("",names(Tennis)[4:21])),
                                    width = 4),
                                box(title = "Select the Model you Want to Make (NOTE: Since this
                  dataset doesn't have any seasonal component to it, a seasonal naive
                  forecast model can't be created)",
                                    selectInput(inputId = "simplemodel", label = "Select a Model Type",
                                                choices = c("","Naive","Mean","Drift")),
                                    numericInput(inputId = "forecastnum",
                                                 label = "How Many Years Ahead Would you Like to Forecast?
                               (If you chose the forecast option)",
                                                 value = ""),
                                    width = 4),
                                actionButton(inputId = "create1", label = "Create!"),
                                DTOutput("simpletable"),
                                plotOutput("simple1graph")),
                        tabItem(tabName = "ets",
                                box(title = "Select the Output you want to See with your Exponential
                  Smoothing Model",
                                    awesomeRadio(inputId = "etsgraph",
                                                 label = NULL,
                                                 choices = c("Forecast", "Components", "Residuals", "Accuracy")),
                                    width = 4),
                                box(title = "Select the Parameters you Want for your Model",
                                    selectInput(inputId = "etsplayer", label = "Select a Player",
                                                choices = c("",unique(Tennis$Player))),
                                    selectInput(inputId = "etsstat", label = "Select a Statistic",
                                                choices = c("",names(Tennis)[4:21])),
                                    width = 4),
                                box(title = "How Many Years Ahead Would you Like to Forecast?
                               (If you chose the forecast option)",
                                    numericInput(inputId = "etsnum",
                                                 label = NULL,
                                                 value = ""),
                                    width = 4),
                                actionButton(inputId = "create3", label = "Create!"),
                                DTOutput("etstable"),
                                plotOutput("ets1graph")),
                        tabItem(tabName = "arima",
                                box(title = "Select the Output you want to See with your ARIMA Model",
                                    awesomeRadio(
                                      inputId = "arimagraph",
                                      label = NULL,
                                      choices = c("Report","Forecast", "Residuals", "Accuracy")),
                                    width = 4),
                                box(title = "Select the Parameters you Want for your Model",
                                    selectInput(inputId = "arimaplayer", label = "Select a Player",
                                                choices = c("",unique(Tennis$Player))),
                                    selectInput(inputId = "arimastat", label = "Select a Statistic",
                                                choices = c("",names(Tennis)[4:21])),
                                    width = 4),
                                box(title = "How Many Years Ahead Would you Like to Forecast?
                               (If you chose the forecast option)",
                                    numericInput(inputId = "arimanum",
                                                 label = NULL,
                                                 value = ""),
                                    width = 4),
                                actionButton(inputId = "create4", label = "Create!"),
                                br(), br(), br(), br(), br(), br(),
                                DTOutput("arimatable"),
                                verbatimTextOutput("arimareport"),
                                plotOutput("arima1graph")),
                        tabItem(tabName = "custarima",
                                box(title = "Select the Output you want to See with your ARIMA Model",
                                    awesomeRadio(
                                      inputId = "custarimagraph",
                                      label = NULL,
                                      choices = c("Report","Forecast", "Residuals", "Accuracy")),
                                    width = 3),
                                box(title = "What is your chosen pdq?",
                                    numericInput(inputId = "arimap",
                                                 label = "p",
                                                 value = ""),
                                    numericInput(inputId = "arimad",
                                                 label = "d",
                                                 value = ""),
                                    numericInput(inputId = "arimaq",
                                                 label = "q",
                                                 value = ""),
                                    width = 3),
                                box(title = "Select the Parameters you Want for your Model",
                                    selectInput(inputId = "custarimaplayer", label = "Select a Player",
                                                choices = c("",unique(Tennis$Player))),
                                    selectInput(inputId = "custarimastat", label = "Select a Statistic",
                                                choices = c("",names(Tennis)[4:21])),
                                    width = 3),
                                box(title = "How Many Years Ahead Would you Like to Forecast?
                               (If you chose the forecast option)",
                                    numericInput(inputId = "custarimanum",
                                                 label = NULL,
                                                 value = ""),
                                    width = 3),
                                actionButton(inputId = "create7", label = "Create!"),
                                br(), br(), br(), br(), br(), br(),
                                DTOutput("custarimatable"),
                                verbatimTextOutput("custarimareport"),
                                plotOutput("custarima1graph")),
                        tabItem(tabName = "reg",
                                box(title = "Select the Output you want to See with your Linear Regression Model",
                                    awesomeRadio(
                                      inputId = "reggraph",
                                      label = NULL,
                                      choices = c("Forecast", "Residuals", "Accuracy")),
                                    width = 4),
                                box(title = "Select the Parameters you Want for your Model",
                                    selectInput(inputId = "regplayer", label = "Select a Player",
                                                choices = c("",unique(Tennis$Player))),
                                    selectInput(inputId = "regstat", label = "Select a Statistic",
                                                choices = c("",names(Tennis)[4:21])),
                                    width = 4),
                                box(title = "How Many Years Ahead Would you Like to Forecast?
                               (If you chose the forecast option)",
                                    numericInput(inputId = "regnum",
                                                 label = NULL,
                                                 value = ""),
                                    width = 4),
                                actionButton(inputId = "create6", label = "Create!"),
                                DTOutput("regtable"),
                                plotOutput("reg1graph")),
                        tabItem(tabName = "linear",
                                box(title = "Select the Output you want to See with your
                  Linear Regression Model",
                                    awesomeRadio(
                                      inputId = "lineargraph",
                                      label = NULL,
                                      choices = c("Forecast", "Residuals", "Accuracy")),
                                    width = 4),
                                box(title = "Select the Parameters you Want for your Model",
                                    selectInput(inputId = "linearplayer", label = "Select a Player",
                                                choices = c("",unique(Tennis$Player))),
                                    selectInput(inputId = "linearstat", label = "Select a Linear Model",
                                                choices = c("", 
                                                            "% Total Points Won ~ % Return Points Won",
                                                            "% Total Points Won ~ % Total Service Points Won",
                                                            "% Service Games Won ~ % 1st Serve Points Won",
                                                            "% Service Games Won ~ % 2nd Serve Points Won",
                                                            "Break Points Opportunities ~ % 1st Serve Return Points Won",
                                                            "Break Points Opportunities ~ % 2nd Serve Return Points Won",
                                                            "% Return Games Won ~ % 1st Serve Return Points Won",
                                                            "% Return Games Won ~ % 2nd Serve Return Points Won",
                                                            "% Return Points Won ~ % 1st Serve Return Points Won",
                                                            "% Return Points Won ~ % 2nd Serve Return Points Won")),
                                    width = 4),
                                box(title = "Select your Value of x for Your Forecast",
                                    numericInput(inputId = "linearnum",
                                                 label = NULL,
                                                 value = ""),
                                    width = 4),
                                actionButton(inputId = "create5", label = "Create!"),
                                DTOutput("lineartable"),
                                plotOutput("linear1graph"))
                      ))
)